#application url
url_old = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
url=http://localhost/orangehrm/web/index.php/auth/login
#browser configuration
browser= chrome

#credentials
username=orangehrm_mayankkumar
password=Mayank123,

#implicitwait(in sec)
implicitWait=10

#explicitwait
explicitWait=25